name: Copy README.md

on:
  push:
    branches:
      - gh-pages

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Copy README.md from master
        env: 
          CI_COMMIT_MESSAGE: Copy README.md from master
          CI_COMMIT_AUTHOR: Continuous Integration
        run: |
          git checkout refs/remotes/origin/master README.md
          git diff --staged --quiet || (git commit -m "${{ env.CI_COMMIT_MESSAGE }}" && git push)
